version: '3'
services:
  
  server:
    container_name: dev_api
    working_dir: /code
    ports: 
      - 5000:5000  ##Temporary change (testing this on AWS)
    environment: 
      - PORT= 5000
    depends_on:
      - db
    command: bash -c "cd server && npm install && npm start" ##cd into server (inside container) then npm i & start

  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=futureproof
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_PASSWORD=userpass
volumes:
  dbdata:
networks: 
  default:
    name: app_dev
